### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by kiddico** [MultiCoreNop/Logitech-G19-Linux-Daemon#1]
Hey, I was jsut wondering if this project is in anyway still active. Obviously you've not commited since 2010, but maybe you decided to keep the project for yourself haha. If you're not interested in the project anymore I was concidereing picking it up, and trying to finish it, as there is (still!) no good g19 support.

I know an issue report isn't a great method of contact, but it was the only was I could think of to send you a message.

**Comment by MultiCoreNop** [comment]
Hi, really sorry about the 'somewhat' late reply... I could not access my GMail account registered to Github, because of I don't know why (just could not sign in). Worked today for the first time..
To answer your question: No, I did not do any 'secret coding'. ;)
There was a project, that I believe added G19 support based on my code though.

**Comment by kiddico** [comment]
Haha it's cool. I ended up ditching the G19 anyways, but it would be fun to play with sometime.

Do you happen to have a link to the other project?
